/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Color;
import javax.swing.event.ChangeListener;

/**
 * Clase que representa la paleta de colores.
 * Extiende de javax.swing.JFrame
 * @author Francisco Manuel Sánchez Ramos
 */
public class Colores extends javax.swing.JFrame {

    /**
     * Crea un objeto Colores y lo inicializa al color que hay
     * marcado para el trazo o el relleno por defecto según el boton
     * de los dos que esté seleccionado.
     * @param color Variable Color que indica el color al que se debe 
     * iniciarlizar la paleta de colores cuando se llame.
     */
    public Colores(Color color) {
        initComponents();
        colores.setColor(color);
    }
    
    /**
     * Método para obtener el color que se ha seleccionado en la paleta de
     * colores. 
     * Inicialmente toma el valor del color seleccionado.
     * El selector de color dispara un evento "change" si el usuario 
     * cambia el color del selector.
     * @param listener Variable que espera a que se produzca un evento de 
     * cambio de color
     */
    public void añadirColor(ChangeListener listener){
        colores.getSelectionModel().addChangeListener(listener);
    }
    
    /**
     * Método que devuelve un color.
     * @return El color.
     */
    public Color getColor(){
        return colores.getColor();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colores = new javax.swing.JColorChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().add(colores, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser colores;
    // End of variables declaration//GEN-END:variables
}
