/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/**
 * Clase que representa una ventana interna.
 * Hereda de la clase javax.swing.JInternalFrame.
 * @author Francisco Manuel Sánchez Ramos.
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    /**
     * Crea un objeto VentanaIngerna.
     */
    
    public VentanaInterna() {
        initComponents();
    }
    
    /**
     * Método para devolver el lienzo de una imagen.
     * @return El lienzo de una imagen.
     */
    public lienzoImagen getLienzo(){
        return this.lienzoImagen1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzoImagen1 = new proyectofinal.lienzoImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jScrollPane1.setViewportView(lienzoImagen1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private proyectofinal.lienzoImagen lienzoImagen1;
    // End of variables declaration//GEN-END:variables
}
