/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import sm.sound.SMRecorder;
import sm.sound.SMSoundRecorder;

/**
 * Clase que representa una ventana interna grabación.
 * Hereda de javax.swing.JinternalFrame.
 * @author Francisco Manuel Sánchez Ramos.
 */
public class VentanaInternaGrabacion extends javax.swing.JInternalFrame {

    /**
     * Variable de tipo SMRecorder.
     */
    SMRecorder recorder;
    
    /**
     * Crea un objeto de tipo VentanaInternaGrabación a partir de un nombre
     * de fichero que le pasemos.
     * @param f Variable de tipo File que representa el nombre del fichero.
     */
    public VentanaInternaGrabacion(File f) {
        initComponents();
        
        recorder = new SMSoundRecorder(f);
        
        if(recorder!=null){
            LineListener lineListener = new LineListener(){
                @Override
                public void update(LineEvent event){
                    if(event.getType()==LineEvent.Type.START){

                     } 
                    if(event.getType()==LineEvent.Type.STOP){
                        botonStop.setSelected(true);
                        botonGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/RecordPressed_48x48.png")));
                        botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/StopDisabled_48x48.png")));
                        
                    }
                }
            };
            recorder.setLineListener(lineListener);
       } 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelSeparador2 = new javax.swing.JSplitPane();
        botonGrabar = new javax.swing.JToggleButton();
        botonStop = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(400, 100));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panelSeparador2.setDividerLocation(190);

        buttonGroup1.add(botonGrabar);
        botonGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/RecordPressed_48x48.png"))); // NOI18N
        botonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGrabarActionPerformed(evt);
            }
        });
        panelSeparador2.setLeftComponent(botonGrabar);

        buttonGroup1.add(botonStop);
        botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/StopDisabled_48x48.png"))); // NOI18N
        botonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStopActionPerformed(evt);
            }
        });
        panelSeparador2.setRightComponent(botonStop);

        getContentPane().add(panelSeparador2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGrabarActionPerformed
        // TODO add your handling code here:
        if(recorder!=null){
            recorder.record();
            botonGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/RecordDisabled_48x48.png")));
            botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/StopNormalRed_48x48.png")));
        }
    }//GEN-LAST:event_botonGrabarActionPerformed

    private void botonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStopActionPerformed
        // TODO add your handling code here:
        if(recorder!=null)
            recorder.stop();
    }//GEN-LAST:event_botonStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonGrabar;
    private javax.swing.JToggleButton botonStop;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSplitPane panelSeparador2;
    // End of variables declaration//GEN-END:variables
}
